import { AcademicEvent } from "@/types";

export const MOCK_EVENTS: AcademicEvent[] = [
  {
    id: "evt_1",
    title: "XVIII Semana Acadêmica do Curso de Psicologia",
    description: "Palestras magnas, minicursos práticos e mesas redondas sobre ética, saúde mental contemporânea e atuação clínica com emissão de certificado.",
    date: "2026-10-19",
    time: "19h00 às 22h00",
    location: "Teatro Adelaide Konder & Auditório do Bloco F1",
    category: "Acadêmico",
    entityOwner: "centro_academico",
    status: "inscricoes_abertas",
    workloadHours: 30,
    imageUrl: "/images/evento-palestra.jpg",
    registrationUrl: "https://elis.univali.br",
    additionalInfo: "Certificação oficial UNIVALI de 30 horas complementares de extensão.",
  },
  {
    id: "evt_3",
    title: "Clássico Universitário: Psicologia vs Direito (Futsal Masculino & Feminino)",
    description: "Rodada decisiva dos Jogos Acadêmicos UNIVALI (JAU). Venha com a bateria Guaxas apoiar nossos atletas na quadra principal.",
    date: "2026-10-14",
    time: "20h30",
    location: "Ginásio de Esportes UNIVALI - Bloco 21",
    category: "Esportivo",
    entityOwner: "atletica",
    status: "confirmado",
    imageUrl: "/images/evento-futsal.jpg",
    additionalInfo: "Acesso livre para toda a comunidade acadêmica. Vista o manto oficial Guaxas!",
  },
  {
    id: "evt_2",
    title: "Cine-Debate: Nise - O Coração da Loucura & Antipsiquiatria",
    description: "Exibição comentada do filme seguida de mesa de discussão com docentes convidados sobre a reforma psiquiátrica brasileira.",
    date: "2026-10-08",
    time: "18h30 às 21h00",
    location: "Sala de Projeção Multimídia - Bloco B2",
    category: "Centro Acadêmico",
    entityOwner: "centro_academico",
    status: "confirmado",
    workloadHours: 4,
    registrationUrl: "#",
    additionalInfo: "Entrada mediante doação voluntária de 1kg de alimento não perecível para o Trote Solidário.",
  },
  {
    id: "evt_4",
    title: "Oficina Prática de Elaboração de Laudos e Pareceres Psicológicos",
    description: "Capacitação técnica voltada para acadêmicos dos estágios básicos e específicos sobre as resoluções vigentes do Conselho Federal de Psicologia.",
    date: "2026-10-24",
    time: "09h00 às 12h00",
    location: "Laboratório de Avaliação Psicológica - Bloco F1",
    category: "Acadêmico",
    entityOwner: "centro_academico",
    status: "inscricoes_abertas",
    workloadHours: 6,
    registrationUrl: "https://elis.univali.br",
    additionalInfo: "Vagas limitadas a 35 estudantes dos períodos finais.",
  },
  {
    id: "evt_5",
    title: "Churrasco de Integração & Boas-Vindas da Psicologia (A.A.A.P.U. Guaxas)",
    description: "Confraternização dos estudantes de Psicologia, recepção aos calouros, música ao vivo, jogos e integração entre todos os períodos.",
    date: "2026-11-07",
    time: "13h00 às 19h00",
    location: "Espaço Recreativo dos Professores (Associação UNIVALI)",
    category: "Social",
    entityOwner: "atletica",
    status: "em_breve",
    additionalInfo: "Ingressos antecipados com a Diretoria de Eventos da Atlética.",
  },
  {
    id: "evt_6",
    title: "Roda de Conversa: Saúde Mental do Universitário e Prevenção ao Burnout",
    description: "Encontro aberto organizado em parceria com o Programa Acolher para debater estratégias de manejo de estresse na rotina de estágios e TCC.",
    date: "2026-10-28",
    time: "17h30 às 19h00",
    location: "Tenda Cultural em frente ao Bloco F1",
    category: "Centro Acadêmico",
    entityOwner: "centro_academico",
    status: "confirmado",
    workloadHours: 2,
    additionalInfo: "Aberto a estudantes de qualquer período e turno.",
  },
  {
    id: "evt_7",
    title: "Peneira e Seletiva de Novos Atletas Guaxas 2027",
    description: "Avaliação técnica para novos integrantes dos times de Futsal, Vôlei, Basquete 3x3 e Handebol da Atlética.",
    date: "2026-11-21",
    time: "09h00 às 12h00",
    location: "Ginásio de Esportes UNIVALI",
    category: "Esportivo",
    entityOwner: "atletica",
    status: "em_breve",
  },
];
